Add Dutch Translation
teambluemods/healthmod-translations pull request #6
Opened 2020-12-29 22:17 UTC by brammie15

2020-12-29 22:25 UTC, xf8b approved these changes
i would say to not translate `HealthMod` and to translate `config value` since `config value` isn't going to be changed
also it seems as though the capitalization is wonk, not sure if its google translate being jank

try to keep the translation as close to minecraft, so don't put periods after the death messages

otherwise looks good

2020-12-30 17:39 UTC, ilja615 reviewed
I make review because xf8b asked if i make review soo here it is and thank you brammie voor making the translate, it is very good except for this 4 small points i found.

2020-12-30 17:39 UTC, ilja615 commented on nl_nl.json
> +  "text.autoconfig.healthmod.category.woundInfection": "Wonde Infectie",
Ik denk dat het niet "Wonde Infectie" maar "Wond Infectie" moet zijn.
I think it has to be not "Wonde Infectie" but "Wond Infectie

2020-12-30 17:39 UTC, ilja615 commented on nl_nl.json
> +  "item.healthmod.soap": "zeepbar",
Ik denk dat "zeepbar" moet veranderd worden in "Zeepbar" omdat item altijd met hoofdletter begint.
I think "zeepbar" has to be changed to "Zeepbar" because item always has capital letter start.

2020-12-30 17:39 UTC, ilja615 commented on nl_nl.json
> +  "death.attack.wound_infection": "%1$s is gestorven van een wond infectie.",
Ik denk dat "van" beter kan worden vervangen met "door".
I think that "van" better can be replaced by "door".

2020-12-30 17:39 UTC, ilja615 commented on nl_nl.json
> +  "death.attack.wound_infection.player": "%1$s is gestorven van een wond infectie."
Ik denk dat hier ook "van" beter kan worden vervangen met "door".
I think that here also "van" better can be replaced by "door".

2020-12-30 17:42 UTC, xf8b requested changes
ignore this i am adding suggestions consistent with my previous review

2020-12-30 17:42 UTC, xf8b commented on nl_nl.json
> +  "itemGroup.healthmod.all": "GezondheidsMod",
```suggestion
  "itemGroup.healthmod.all": "HealthMod",
```

2020-12-30 17:42 UTC, xf8b commented on nl_nl.json
> +  "text.autoconfig.healthmod.title": "GezondheidsMod Configuratie",
```suggestion
  "text.autoconfig.healthmod.title": "HealthMod Configuratie",
```

2020-12-30 17:42 UTC, xf8b commented on nl_nl.json
> +  "death.attack.wound_infection.player": "%1$s is gestorven van een wond infectie."
```suggestion
  "death.attack.wound_infection.player": "%1$s is gestorven van een wond infectie"
```

2020-12-30 17:42 UTC, xf8b commented on nl_nl.json
> +  "death.attack.wound_infection": "%1$s is gestorven van een wond infectie.",
```suggestion
  "death.attack.wound_infection": "%1$s is gestorven van een wond infectie",
```

2020-12-30 17:55 UTC, xf8b commented on nl_nl.json
> +  "text.autoconfig.healthmod.category.woundInfection": "Wonde Infectie",
```suggestion
  "text.autoconfig.healthmod.category.woundInfection": "Wond Infectie",
```

2020-12-30 17:55 UTC, xf8b commented on nl_nl.json
> +  "item.healthmod.soap": "zeepbar",
```suggestion
  "item.healthmod.soap": "Zeepbar",
```

2020-12-30 17:55 UTC, xf8b commented on nl_nl.json
> +  "death.attack.wound_infection": "%1$s is gestorven van een wond infectie.",
```suggestion
  "death.attack.wound_infection": "%1$s is gestorven door een wond infectie.",
```

2020-12-30 17:55 UTC, xf8b commented on nl_nl.json
> +  "death.attack.wound_infection.player": "%1$s is gestorven van een wond infectie."
```suggestion
  "death.attack.wound_infection.player": "%1$s is gestorven door een wond infectie."
```

2021-01-01 03:20 UTC, xf8b commented
update when ready

2021-01-25 06:37 UTC, xf8b approved these changes
fuck it

2021-01-25 06:37 UTC, xf8b commented
small note to self: easter egg translations are missing

2021-01-25 06:37 UTC, merged